version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '[%(asctime)s %(levelname)s - %(name)s] %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - default
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
  propagate: no